# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# TODO: enable pre-commit CI once we make the repo public
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.2
    hooks:
    - id: cmakelint
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.8.2
    hooks:
      - id: gersemi
