name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.toolchain.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - name: "GCC 7"
            cc: "gcc-7"
            cxx: "g++-7"
            dependencies: "gcc-7 g++-7"
          - name: "GCC 8"
            cc: "gcc-8"
            cxx: "g++-8"
            dependencies: "gcc-8 g++-8"
          - name: "GCC 9"
            cc: "gcc-9"
            cxx: "g++-9"
            dependencies: "gcc-9 g++-9"
          - name: "GCC 10"
            cc: "gcc-10"
            cxx: "g++-10"
            dependencies: "gcc-10 g++-10"
          - name: "GCC 11"
            cc: "gcc-11"
            cxx: "g++-11"
            dependencies: "gcc-11 g++-11"
          - name: "Clang 6",
            cc: "clang-6.0",
            cxx: "clang++-6.0",
            dependencies: "clang-6.0",
          - name: "Clang 7",
            cc: "clang-7",
            cxx: "clang++-7",
            dependencies: "clang-7",
          - name: "Clang 8",
            cc: "clang-8",
            cxx: "clang++-8",
            dependencies: "clang-8",
          - name: "Clang 9",
            cc: "clang-9",
            cxx: "clang++-9",
            dependencies: "clang-9",
          - name: "Clang 10",
            cc: "clang-10",
            cxx: "clang++-10",
            dependencies: "clang-10",
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install compiler.
        run: sudo apt install -yq ${{ matrix.toolchain.dependencies }}
      - name: Configure CMake project.
        run: CC=${{ matrix.toolchain.cc }} CXX=${{ matrix.toolchain.cxx }} cmake -B build
      - name: Build CMake project.
        run: cmake --build build
