name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.toolchain.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - name: "GCC 10"
            cc: "gcc-10"
            cxx: "g++-10"
            dependencies: "gcc-10 g++-10"
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install compiler.
        run: sudo apt install -yq ${{ matrix.toolchain.dependencies }}
      - name: Configure CMake project.
        run: CC=${{ matrix.toolchain.cc }} CXX=${{ matrix.toolchain.cxx }} cmake -B build
      - name: Build CMake project.
        run: cmake --build build
