name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.toolchain.name }} (${{ matrix.toolchain.os }})
    runs-on: ${{ matrix.toolchain.os }}
    strategy:
      matrix:
        toolchain:
          - name: "GCC 10"
            cc: "gcc-10"
            cxx: "g++-10"
            dependencies: "gcc-10 g++-10"
            os: "ubuntu-20.04"
          - name: "GCC 11"
            cc: "gcc-11"
            cxx: "g++-11"
            dependencies: "gcc-11 g++-11"
            os: "ubuntu-20.04"
          - name: "GCC 12"
            cc: "gcc-12"
            cxx: "g++-12"
            dependencies: "gcc-12 g++-12"
            os: "ubuntu-22.04"
          - name: "Clang 10"
            cc: "clang-10"
            cxx: "clang++-10"
            dependencies: "clang-10"
            os: "ubuntu-20.04"
          - name: "Clang 11"
            cc: "clang-11"
            cxx: "clang++-11"
            dependencies: "clang-11"
            os: "ubuntu-22.04"
          - name: "Clang 12"
            cc: "clang-12"
            cxx: "clang++-12"
            dependencies: "clang-12"
            os: "ubuntu-22.04"
          - name: "Clang 13"
            cc: "clang-13"
            cxx: "clang++-13"
            dependencies: "clang-13"
            os: "ubuntu-22.04"
          - name: "Clang 14"
            cc: "clang-14"
            cxx: "clang++-14"
            dependencies: "clang-14"
            os: "ubuntu-22.04"
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install compiler.
        run: sudo apt-get install -yq ${{ matrix.toolchain.dependencies }} cmake
      - name: Configure CMake project.
        run: CC=${{ matrix.toolchain.cc }} CXX=${{ matrix.toolchain.cxx }} cmake -B build
      - name: Build CMake project.
        run: cmake --build build
  lint:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install linters.
        run: sudo apt-get install -yq cmake clang-14 clang-tidy-14 clang-format-14 cppcheck cpplint
      - name: Configure CMake project.
        run: CC=${{ matrix.toolchain.cc }} CXX=${{ matrix.toolchain.cxx }} cmake -B build
